/**
 * Round-trip tests for RFC-014 artifact ↔ file serialization.
 * Pure functions, no IO. Verifies that emitting an artifact to its file shape
 * and parsing it back preserves identity and all meaningful fields.
 */

import { test } from 'node:test'
import assert from 'node:assert/strict'
import {
  markdownArtifactToText,
  parseMarkdownArtifact,
  dataArtifactToSidecar,
  dataArtifactFromSidecar,
  paperToBibEntry,
  paperToSidecarEntry,
  parsePaperFile,
  parsePaperLibrary
} from '../artifact-files.js'
import { parseFrontMatter } from '../front-matter.js'
import type {
  NoteArtifact,
  WebContentArtifact,
  ToolOutputArtifact,
  DataArtifact,
  PaperArtifact,
  Provenance
} from '../../types.js'

const prov: Provenance = {
  source: 'agent',
  sessionId: 'sess-1',
  agentId: 'coordinator',
  extractedFrom: 'agent-response',
  messageId: 'msg-9'
}

test('note round-trips through markdown front-matter', () => {
  const note: NoteArtifact = {
    id: 'note-uuid-1',
    type: 'note',
    title: 'Threshold theorem',
    tags: ['surface-code', 'ecc'],
    summary: 'why d=3 tolerates one error',
    provenance: prov,
    createdAt: '2026-05-24T10:00:00.000Z',
    updatedAt: '2026-05-24T11:00:00.000Z',
    content: '# Body\n\nLine one.\n\n- bullet\n\nEnd.'
  }
  const text = markdownArtifactToText(note)
  const back = parseMarkdownArtifact(text) as NoteArtifact
  assert.equal(back.type, 'note')
  assert.deepEqual(back, note)
})

test('web-content round-trips', () => {
  const wc: WebContentArtifact = {
    id: 'wc-1',
    type: 'web-content',
    title: 'A page',
    tags: [],
    provenance: prov,
    createdAt: '2026-05-24T10:00:00.000Z',
    updatedAt: '2026-05-24T10:00:00.000Z',
    url: 'https://example.com/x',
    content: 'scraped **markdown** body',
    fetchedAt: '2026-05-24T09:59:00.000Z'
  }
  const back = parseMarkdownArtifact(markdownArtifactToText(wc)) as WebContentArtifact
  assert.deepEqual(back, wc)
})

test('tool-output round-trips', () => {
  const to: ToolOutputArtifact = {
    id: 'to-1',
    type: 'tool-output',
    title: 'run log',
    tags: ['run'],
    provenance: prov,
    createdAt: '2026-05-24T10:00:00.000Z',
    updatedAt: '2026-05-24T10:00:00.000Z',
    toolName: 'data-analyze',
    outputPath: 'results/out.csv',
    outputText: 'rows: 42\nok'
  }
  const back = parseMarkdownArtifact(markdownArtifactToText(to)) as ToolOutputArtifact
  assert.deepEqual(back, to)
})

test('plain markdown without rp front-matter is NOT a managed artifact', () => {
  assert.equal(parseMarkdownArtifact('# Just a readme\n\nhello'), null)
  assert.equal(parseMarkdownArtifact('---\ntitle: x\n---\nbody'), null) // has fm but no rp.id
})

test('data round-trips through sidecar', () => {
  const data: DataArtifact = {
    id: 'data-1',
    type: 'data',
    title: 'experiment.csv',
    tags: ['raw'],
    summary: 'run 1',
    provenance: prov,
    createdAt: '2026-05-24T10:00:00.000Z',
    updatedAt: '2026-05-24T10:00:00.000Z',
    filePath: 'data/experiment.csv',
    mimeType: 'text/csv',
    schema: { columns: [{ name: 'x', type: 'number' }], rowCount: 10 },
    runId: 'r-1',
    runLabel: 'baseline'
  }
  const sidecar = dataArtifactToSidecar(data)
  const back = dataArtifactFromSidecar(sidecar, 'data/experiment.csv') as DataArtifact
  assert.deepEqual(back, data)
})

test('paper round-trips through .bib + sidecar (incl. tricky authors)', () => {
  const paper: PaperArtifact = {
    id: 'paper-uuid-1',
    type: 'paper',
    title: 'Surface code thresholds',
    tags: ['qec'],
    summary: 'key result',
    provenance: { source: 'import', sessionId: 'unknown', extractedFrom: 'file-import' },
    createdAt: '2026-05-24T10:00:00.000Z',
    updatedAt: '2026-05-24T10:00:00.000Z',
    citeKey: 'chen2025surface',
    bibtex: '', // empty → field-based .bib emit (brace-literal authors round-trip exactly)
    bibtexIsAutoGenerated: false,
    doi: '10.1000/xyz',
    authors: ['Jane Q. Chen', 'A. van der Berg', 'Wei Zhang'],
    abstract: 'We show that ...',
    year: 2025,
    venue: 'Nature Physics',
    url: 'https://example.com/p',
    pdfUrl: 'https://example.com/p.pdf',
    searchKeywords: ['surface code', 'threshold'],
    externalSource: 'literature-search',
    relevanceScore: 0.82,
    citationCount: 41,
    enrichmentSource: 'crossref',
    enrichedAt: '2026-05-24T09:00:00.000Z',
    subTopic: 'thresholds',
    keyFindings: ['finding a', 'finding b'],
    relevanceJustification: 'central',
    addedInRound: 'R-01',
    addedByTask: 'deep_literature_study',
    fulltextPath: 'cache/x.md',
    identityConfidence: 'high',
    arxivId: '2501.00001',
    pubmedId: '12345',
    pmcId: 'PMC678',
    semanticScholarId: 'ss-1'
  }

  const bibEntry = paperToBibEntry(paper)
  const back = parsePaperFile(bibEntry, paperToSidecarEntry(paper))!

  assert.ok(back, 'paper should parse back')
  // identity + standard fields from .bib
  assert.equal(back.id, paper.id)
  assert.equal(back.citeKey, paper.citeKey)
  assert.equal(back.title, paper.title)
  assert.deepEqual(back.authors, paper.authors) // brace-literals preserve exact strings
  assert.equal(back.year, paper.year)
  assert.equal(back.venue, paper.venue)
  assert.equal(back.doi, paper.doi)
  assert.equal(back.url, paper.url)
  assert.equal(back.abstract, paper.abstract)
  assert.equal(back.arxivId, paper.arxivId)
  // app fields from sidecar
  assert.deepEqual(back.tags, paper.tags)
  assert.equal(back.summary, paper.summary)
  assert.equal(back.relevanceScore, paper.relevanceScore)
  assert.equal(back.citationCount, paper.citationCount)
  assert.deepEqual(back.keyFindings, paper.keyFindings)
  assert.equal(back.fulltextPath, paper.fulltextPath)
  assert.equal(back.pmcId, paper.pmcId)
  assert.equal(back.bibtexIsAutoGenerated, false)
  assert.equal(back.identityConfidence, 'high')
  assert.deepEqual(back.provenance, paper.provenance)
})

test('curated bibtex is used verbatim in the .bib (validated) and preserved exactly', () => {
  const curated =
    '@article{smith2024deep,\n  title = {Deep Nets},\n  author = {Smith, Jane and Doe, John},\n  journal = {JMLR},\n  year = {2024},\n  doi = {10.5/abc},\n  pages = {1--20},\n  publisher = {MIT Press}\n}'
  const paper: PaperArtifact = {
    id: 'pv-1', type: 'paper', title: 'Deep Nets', tags: [], provenance: { source: 'import', sessionId: 'u' },
    createdAt: '2026-05-24T10:00:00.000Z', updatedAt: '2026-05-24T10:00:00.000Z',
    citeKey: 'smith2024deep', bibtex: curated, bibtexIsAutoGenerated: false,
    doi: '10.5/abc', authors: ['Jane Smith', 'John Doe'], abstract: '', year: 2024, venue: 'JMLR'
  }
  const bibEntry = paperToBibEntry(paper)
  // verbatim: the curated-only field `pages`/`publisher` reach the .bib file
  assert.ok(bibEntry.includes('pages = {1--20}'), 'curated extra fields preserved in .bib')
  assert.ok(bibEntry.includes('publisher = {MIT Press}'))
  assert.ok(bibEntry.includes('rp_id = {pv-1}'))

  const back = parsePaperFile(bibEntry, paperToSidecarEntry(paper))!
  assert.ok(back)
  assert.equal(back.bibtex, curated) // exact verbatim from sidecar
  assert.deepEqual(back.authors, ['Jane Smith', 'John Doe'])
  assert.equal(back.year, 2024)
  assert.equal(back.venue, 'JMLR')
})

test('malformed curated bibtex falls back to field-based emit (paper stays readable)', () => {
  const paper: PaperArtifact = {
    id: 'pm-1', type: 'paper', title: 'Salvageable', tags: [], provenance: { source: 'import', sessionId: 'u' },
    createdAt: '2026-05-24T10:00:00.000Z', updatedAt: '2026-05-24T10:00:00.000Z',
    citeKey: 'junk2024', bibtex: '@article{junk2024, ...}', bibtexIsAutoGenerated: false,
    doi: '10.9/z', authors: ['Ann Lee'], abstract: 'ok', year: 2024
  }
  const bibEntry = paperToBibEntry(paper)
  const back = parsePaperFile(bibEntry, paperToSidecarEntry(paper))!
  assert.ok(back, 'paper must remain readable despite malformed curated bibtex')
  assert.equal(back.title, 'Salvageable')   // from structured fields, not the junk
  assert.deepEqual(back.authors, ['Ann Lee'])
})

test('paper library handles multiple entries', () => {
  const mk = (id: string, key: string, title: string): PaperArtifact => ({
    id, type: 'paper', title, tags: [], provenance: { source: 'import', sessionId: 'u' },
    createdAt: '2026-05-24T10:00:00.000Z', updatedAt: '2026-05-24T10:00:00.000Z',
    citeKey: key, bibtex: '', bibtexIsAutoGenerated: true, doi: '', authors: ['A B'], abstract: ''
  })
  const p1 = mk('id1', 'a2020', 'First')
  const p2 = mk('id2', 'b2021', 'Second')
  const bib = paperToBibEntry(p1) + '\n\n' + paperToBibEntry(p2)
  const sidecar = { a2020: paperToSidecarEntry(p1), b2021: paperToSidecarEntry(p2) }
  const papers = parsePaperLibrary(bib, sidecar)
  assert.equal(papers.length, 2)
  const ids = papers.map(p => p.id).sort()
  assert.deepEqual(ids, ['id1', 'id2'])
})

test('front-matter parse/serialize is stable', () => {
  const { data, body } = parseFrontMatter('---\ntitle: Hi\nrp:\n  id: x\n  type: note\n---\n\nbody text')
  assert.equal((data as any).title, 'Hi')
  assert.equal((data as any).rp.id, 'x')
  assert.equal(body.trim(), 'body text')
})
