/**
 * Tests for `bibtexIsAutoGenerated` flag propagation through the generic
 * artifact-create / artifact-update agent tools.
 *
 * Background: RFC-006 review comment #2 noted that the flag was only being
 * set by upsertPaperArtifact — the agent-facing artifact-create and
 * artifact-update tools in entity-tools.ts wrote `bibtex` without touching
 * the flag, so curated content reached disk with the flag defaulting to
 * undefined (treated as "auto-generated" by downstream logic). That left
 * curated BibTeX vulnerable to being silently overwritten by a later
 * BibTeX-import call.
 *
 * These tests pin the corrected behavior:
 *   - artifact-create with non-empty `bibtex` arg → flag = false
 *   - artifact-create without `bibtex` arg (fallback used) → flag = true
 *   - artifact-update with `bibtex` arg → flag is cleared to false
 *   - updatePaperMetadata (enrichment) writing bibtex → flag = false
 */

import { test } from 'node:test'
import assert from 'node:assert/strict'
import { mkdtempSync, rmSync, mkdirSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { createArtifactCreateTool, createArtifactUpdateTool } from '../../tools/entity-tools.js'
import { updatePaperMetadata } from '../../commands/paper-artifact.js'
import { listArtifacts } from '../store.js'
import type { CLIContext, PaperArtifact } from '../../types.js'
import { PATHS } from '../../types.js'

function tmpProject(): string {
  const dir = mkdtempSync(join(tmpdir(), 'pipilot-bibflag-'))
  mkdirSync(join(dir, PATHS.papers), { recursive: true })
  return dir
}

// Teardown tolerance (Windows): an unawaited ledger write can still hold a handle
// on .research-pilot when the test finishes, and Windows refuses rmdir on an open
// handle (ENOTEMPTY) — harmless on POSIX. The assertions already ran, so swallow
// it rather than fail a green test. (Mirrors per-actor-paths.test.ts.)
function cleanup(dir: string): void {
  try {
    rmSync(dir, { recursive: true, force: true, maxRetries: 30, retryDelay: 300 })
  } catch {
    /* temp dir; OS will reclaim it */
  }
}

function getLatestPaper(projectPath: string): PaperArtifact {
  const papers = listArtifacts(projectPath, ['paper']).filter(
    (a): a is PaperArtifact => a.type === 'paper'
  )
  if (papers.length === 0) throw new Error('no papers found')
  // Sort by createdAt descending (newest first).
  return papers.sort((a, b) => b.createdAt.localeCompare(a.createdAt))[0]
}

// ─── artifact-create (entity-tools) ────────────────────────────────────────

test('artifact-create with curated bibtex sets bibtexIsAutoGenerated=false', async () => {
  const project = tmpProject()
  try {
    const tool = createArtifactCreateTool('test-session', project)
    const curated = '@inproceedings{custom2024, title={A Paper}, author={X}, booktitle={NeurIPS}, year={2024}}'
    await tool.execute('call-1', {
      type: 'paper',
      title: 'A Paper',
      authors: ['X'],
      year: 2024,
      doi: '10.1234/x',
      bibtex: curated
    })
    const paper = getLatestPaper(project)
    assert.equal(paper.bibtex, curated)
    assert.equal(paper.bibtexIsAutoGenerated, false)
  } finally {
    cleanup(project)
  }
})

test('artifact-create without bibtex (fallback used) sets bibtexIsAutoGenerated=true', async () => {
  const project = tmpProject()
  try {
    const tool = createArtifactCreateTool('test-session', project)
    await tool.execute('call-2', {
      type: 'paper',
      title: 'Another Paper',
      authors: ['Y'],
      year: 2024,
      doi: '10.1234/y'
      // no bibtex provided
    })
    const paper = getLatestPaper(project)
    assert.ok(paper.bibtex.includes('@article'))  // fallback shape
    assert.equal(paper.bibtexIsAutoGenerated, true)
  } finally {
    cleanup(project)
  }
})

test('artifact-create with empty-string bibtex falls back to auto-generated', async () => {
  const project = tmpProject()
  try {
    const tool = createArtifactCreateTool('test-session', project)
    await tool.execute('call-3', {
      type: 'paper',
      title: 'Yet Another',
      authors: ['Z'],
      year: 2024,
      doi: '10.1234/z',
      bibtex: '   '  // whitespace-only treated as empty
    })
    const paper = getLatestPaper(project)
    assert.equal(paper.bibtexIsAutoGenerated, true)
  } finally {
    cleanup(project)
  }
})

// ─── artifact-update (entity-tools) ────────────────────────────────────────

test('artifact-update with new bibtex clears bibtexIsAutoGenerated', async () => {
  const project = tmpProject()
  try {
    const createTool = createArtifactCreateTool('test-session', project)
    await createTool.execute('call-a', {
      type: 'paper',
      title: 'Paper',
      authors: ['Q'],
      year: 2024,
      doi: '10.1234/q'
      // no bibtex → flag starts at true
    })
    const initial = getLatestPaper(project)
    assert.equal(initial.bibtexIsAutoGenerated, true)

    const updateTool = createArtifactUpdateTool(project)
    const curated = '@article{q2024, title={Paper}, author={Q}, year={2024}, custom={field}}'
    await updateTool.execute('call-b', {
      id: initial.id,
      bibtex: curated
    })

    const after = getLatestPaper(project)
    assert.equal(after.bibtex, curated)
    assert.equal(after.bibtexIsAutoGenerated, false)
  } finally {
    cleanup(project)
  }
})

test('artifact-update without bibtex does not touch the flag', async () => {
  const project = tmpProject()
  try {
    const createTool = createArtifactCreateTool('test-session', project)
    await createTool.execute('call-a', {
      type: 'paper',
      title: 'Paper',
      authors: ['R'],
      year: 2024,
      doi: '10.1234/r',
      bibtex: '@curated{r2024, ...}'
    })
    const initial = getLatestPaper(project)
    assert.equal(initial.bibtexIsAutoGenerated, false)

    const updateTool = createArtifactUpdateTool(project)
    // Update other fields, but not bibtex.
    await updateTool.execute('call-b', {
      id: initial.id,
      abstract: 'A fresh abstract.'
    })

    const after = getLatestPaper(project)
    assert.equal(after.abstract, 'A fresh abstract.')
    assert.equal(after.bibtex, '@curated{r2024, ...}')   // unchanged
    assert.equal(after.bibtexIsAutoGenerated, false)     // unchanged
  } finally {
    cleanup(project)
  }
})

// ─── updatePaperMetadata (enrichment path) ─────────────────────────────────

test('updatePaperMetadata sets bibtexIsAutoGenerated=false when filling bibtex from enrichment', async () => {
  const project = tmpProject()
  try {
    const createTool = createArtifactCreateTool('test-session', project)
    // Start with a paper missing bibtex entirely. We can't actually create a
    // paper with empty bibtex via the tool (fallback fills it), so use the
    // tool then strip the bibtex via a direct update through the tool layer.
    await createTool.execute('call-a', {
      type: 'paper',
      title: 'Paper',
      authors: ['S'],
      year: 2024,
      doi: '10.1234/s'
    })
    const initial = getLatestPaper(project)
    assert.equal(initial.bibtexIsAutoGenerated, true)

    // Simulate enrichment supplying a real bibtex string from CrossRef.
    // updatePaperMetadata's fill-only guard requires existing bibtex to be
    // empty, so we craft a minimal scenario: build a synthetic "existing"
    // object that mimics an artifact with empty bibtex. (In production
    // this state arises when paper-artifact.ts was bypassed — e.g. legacy
    // imports.) For the assertion we only care that when fill happens,
    // the flag flips to false.
    const ctx: CLIContext = { sessionId: 'test-session', projectPath: project }
    const stripped: PaperArtifact = { ...initial, bibtex: '' }
    const enrichedBibtex = '@article{s2024, title={Paper}, author={S. Author}, year={2024}, doi={10.1234/s}, journal={Science}}'
    const result = updatePaperMetadata(
      stripped,
      { bibtex: enrichedBibtex, enrichmentSource: 'crossref' },
      ctx
    )

    assert.equal(result.success, true)
    assert.equal(result.paper!.bibtex, enrichedBibtex)
    assert.equal(result.paper!.bibtexIsAutoGenerated, false)
  } finally {
    cleanup(project)
  }
})
