/**
 * Tests for upsertPaperArtifact's dedup-merge behavior.
 *
 * Pure file-IO tests — no LLM, no network. Verifies the fill-only
 * semantics introduced by RFC-006 §0 (PR-0): when an upsert hits a
 * dedup target, existing populated fields are preserved instead of
 * being overwritten by thinner incoming data.
 *
 * Regression coverage for the bug where:
 *   - a real DOI was silently downgraded to `unknown:<citeKey>`
 *   - an 11-author list was collapsed to ["First, A.", "others"]
 *   - a curated title was overwritten by a filename-derived string
 *   - the Paper Wiki semantic hash flipped on every re-import
 *
 * Also covers the new `wasDeduped` flag (Q4) and the new
 * `bibtexIsAutoGenerated` schema field (Q7).
 */

import { test } from 'node:test'
import assert from 'node:assert/strict'
import { mkdtempSync, rmSync, mkdirSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { upsertPaperArtifact } from '../../commands/paper-artifact.js'
import { listArtifacts } from '../store.js'
import type { CLIContext, PaperArtifact } from '../../types.js'
import { PATHS } from '../../types.js'

function tmpProject(): string {
  const dir = mkdtempSync(join(tmpdir(), 'pipilot-upsert-'))
  // Ensure papers dir exists so listArtifacts doesn't return [] before any write.
  mkdirSync(join(dir, PATHS.papers), { recursive: true })
  return dir
}

function ctx(projectPath: string): CLIContext {
  return { sessionId: 'test-session', projectPath, debug: false }
}

function getPaperById(projectPath: string, id: string): PaperArtifact {
  const papers = listArtifacts(projectPath, ['paper']).filter(
    (a): a is PaperArtifact => a.type === 'paper'
  )
  const found = papers.find(p => p.id === id)
  if (!found) throw new Error(`paper ${id} not found`)
  return found
}

// ─── Baseline: new paper creation ──────────────────────────────────────────

test('creates a new paper when no dedup match exists', () => {
  const project = tmpProject()
  try {
    const result = upsertPaperArtifact(
      'Attention Is All You Need',
      {
        authors: ['Ashish Vaswani', 'Noam Shazeer'],
        year: 2017,
        doi: '10.48550/arXiv.1706.03762',
        venue: 'NeurIPS'
      },
      ctx(project)
    )

    assert.equal(result.success, true)
    assert.equal(result.wasDeduped, false)
    assert.ok(result.paper)
    assert.equal(result.paper!.title, 'Attention Is All You Need')
    assert.equal(result.paper!.doi, '10.48550/arXiv.1706.03762')
    assert.equal(result.paper!.authors.length, 2)
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})

test('new paper without caller-supplied bibtex marks bibtexIsAutoGenerated=true', () => {
  const project = tmpProject()
  try {
    const result = upsertPaperArtifact(
      'A Paper',
      { authors: ['Author, A.'], year: 2024, doi: '10.1234/abc' },
      ctx(project)
    )
    assert.equal(result.success, true)
    assert.equal(result.paper!.bibtexIsAutoGenerated, true)
    assert.ok(result.paper!.bibtex.includes('@article'))
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})

test('new paper with caller-supplied bibtex marks bibtexIsAutoGenerated=false', () => {
  const project = tmpProject()
  try {
    const curatedBibtex = '@article{abc2024, title={A Paper}, author={Author, A.}, year={2024}, doi={10.1234/abc}, keywords={curated}}'
    const result = upsertPaperArtifact(
      'A Paper',
      {
        authors: ['Author, A.'],
        year: 2024,
        doi: '10.1234/abc',
        bibtex: curatedBibtex
      },
      ctx(project)
    )
    assert.equal(result.paper!.bibtexIsAutoGenerated, false)
    assert.equal(result.paper!.bibtex, curatedBibtex)
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})

// ─── Dedup detection ───────────────────────────────────────────────────────

test('dedup by DOI: second upsert returns wasDeduped=true and same id', () => {
  const project = tmpProject()
  try {
    const first = upsertPaperArtifact(
      'Title',
      { authors: ['A'], year: 2024, doi: '10.1234/x' },
      ctx(project)
    )
    const second = upsertPaperArtifact(
      'Title (slightly different)',
      { authors: ['A'], year: 2024, doi: '10.1234/x' },
      ctx(project)
    )
    assert.equal(first.wasDeduped, false)
    assert.equal(second.wasDeduped, true)
    assert.equal(first.paper!.id, second.paper!.id)
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})

test('dedup by citeKey when DOIs differ', () => {
  const project = tmpProject()
  try {
    const first = upsertPaperArtifact(
      'Paper',
      { authors: ['Smith'], year: 2024, citeKey: 'smith2024', doi: '10.1234/x' },
      ctx(project)
    )
    // Second call: no DOI provided → upsert defaults to `unknown:smith2024`,
    // DOI lookup misses; falls through to citeKey lookup which hits.
    const second = upsertPaperArtifact(
      'Paper',
      { authors: ['Smith'], year: 2024, citeKey: 'smith2024' },
      ctx(project)
    )
    assert.equal(second.wasDeduped, true)
    assert.equal(first.paper!.id, second.paper!.id)
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})

test('dedup by title+year fallback when DOI and citeKey both differ', () => {
  const project = tmpProject()
  try {
    const first = upsertPaperArtifact(
      'Exactly This Title',
      { authors: ['A'], year: 2024, doi: '10.1234/x', citeKey: 'a2024' },
      ctx(project)
    )
    const second = upsertPaperArtifact(
      'Exactly This Title',
      { authors: ['A'], year: 2024, doi: '10.5678/y', citeKey: 'b2024' },
      ctx(project)
    )
    assert.equal(second.wasDeduped, true)
    assert.equal(first.paper!.id, second.paper!.id)
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})

// ─── Fill-only regression tests — the core bug PR-0 fixes ─────────────────

test('REGRESSION: real DOI is NOT downgraded to unknown:* by a re-upsert lacking DOI', () => {
  const project = tmpProject()
  try {
    // First write: full data including real DOI.
    const first = upsertPaperArtifact(
      'Attention Is All You Need',
      {
        authors: ['Vaswani', 'Shazeer', 'Parmar', 'Uszkoreit', 'Jones'],
        year: 2017,
        doi: '10.48550/arxiv.1706.03762',
        citeKey: 'vaswani2017'
      },
      ctx(project)
    )

    // Second write: thinner data, no DOI. Simulates a stripped Zotero export
    // or a re-import of a partial .bib. Pre-fix this overwrote the DOI with
    // `unknown:vaswani2017`.
    const second = upsertPaperArtifact(
      'Attention Is All You Need',
      {
        authors: ['Vaswani, A.', 'others'],
        year: 2017,
        citeKey: 'vaswani2017'
        // no DOI
      },
      ctx(project)
    )

    assert.equal(second.wasDeduped, true)
    const stored = getPaperById(project, first.paper!.id)
    assert.equal(stored.doi, '10.48550/arxiv.1706.03762', 'real DOI must survive')
    assert.ok(!stored.doi.startsWith('unknown:'), 'DOI must not be a placeholder')
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})

test('REGRESSION: full author list is NOT collapsed by a thinner re-upsert', () => {
  const project = tmpProject()
  try {
    const first = upsertPaperArtifact(
      'Paper',
      {
        authors: ['Ashish Vaswani', 'Noam Shazeer', 'Niki Parmar', 'Jakob Uszkoreit'],
        year: 2017,
        doi: '10.1234/x'
      },
      ctx(project)
    )
    upsertPaperArtifact(
      'Paper',
      { authors: ['Vaswani'], year: 2017, doi: '10.1234/x' },
      ctx(project)
    )
    const stored = getPaperById(project, first.paper!.id)
    assert.equal(stored.authors.length, 4, 'four-author list must survive')
    assert.equal(stored.authors[0], 'Ashish Vaswani')
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})

test('REGRESSION: curated title is NOT overwritten by a filename-derived re-upsert', () => {
  const project = tmpProject()
  try {
    const first = upsertPaperArtifact(
      'Attention Is All You Need',
      { authors: ['Vaswani'], year: 2017, doi: '10.1234/x' },
      ctx(project)
    )
    upsertPaperArtifact(
      'paper',  // imagine a manual file-drop using a bad filename
      { authors: ['Vaswani'], year: 2017, doi: '10.1234/x' },
      ctx(project)
    )
    const stored = getPaperById(project, first.paper!.id)
    assert.equal(stored.title, 'Attention Is All You Need')
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})

test('REGRESSION: curated bibtex is NOT overwritten by a re-upsert with no caller-provided bibtex', () => {
  const project = tmpProject()
  try {
    const curated = '@article{x, title={...}, custom_field={preserved}}'
    const first = upsertPaperArtifact(
      'Paper',
      { authors: ['A'], year: 2024, doi: '10.1234/x', bibtex: curated },
      ctx(project)
    )
    assert.equal(first.paper!.bibtexIsAutoGenerated, false)

    upsertPaperArtifact(
      'Paper',
      { authors: ['A'], year: 2024, doi: '10.1234/x' /* no bibtex */ },
      ctx(project)
    )
    const stored = getPaperById(project, first.paper!.id)
    assert.equal(stored.bibtex, curated, 'curated bibtex must survive')
    assert.equal(stored.bibtexIsAutoGenerated, false)
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})

// ─── Fill-only progression: empty/placeholder fields DO get filled ───────

test('fill-only: empty abstract gets filled on re-upsert', () => {
  const project = tmpProject()
  try {
    const first = upsertPaperArtifact(
      'Paper',
      { authors: ['A'], year: 2024, doi: '10.1234/x' /* no abstract */ },
      ctx(project)
    )
    assert.equal(first.paper!.abstract, '')

    upsertPaperArtifact(
      'Paper',
      {
        authors: ['A'],
        year: 2024,
        doi: '10.1234/x',
        abstract: 'A useful summary.'
      },
      ctx(project)
    )
    const stored = getPaperById(project, first.paper!.id)
    assert.equal(stored.abstract, 'A useful summary.')
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})

test('fill-only: unknown:* DOI gets replaced by real DOI', () => {
  const project = tmpProject()
  try {
    // First write: no DOI → upsert defaults to `unknown:<citeKey>`.
    const first = upsertPaperArtifact(
      'Paper',
      { authors: ['Smith'], year: 2024, citeKey: 'smith2024' /* no doi */ },
      ctx(project)
    )
    assert.ok(first.paper!.doi.startsWith('unknown:'))

    // Second write supplies the real DOI.
    upsertPaperArtifact(
      'Paper',
      {
        authors: ['Smith'],
        year: 2024,
        citeKey: 'smith2024',
        doi: '10.1234/real'
      },
      ctx(project)
    )
    const stored = getPaperById(project, first.paper!.id)
    assert.equal(stored.doi, '10.1234/real')
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})

test('fill-only: ["Unknown"] author placeholder gets replaced by real authors', () => {
  const project = tmpProject()
  try {
    const first = upsertPaperArtifact(
      'Paper',
      { /* no authors */ year: 2024, doi: '10.1234/x' },
      ctx(project)
    )
    assert.deepEqual(first.paper!.authors, ['Unknown'])

    upsertPaperArtifact(
      'Paper',
      {
        authors: ['Real, A.', 'Real, B.'],
        year: 2024,
        doi: '10.1234/x'
      },
      ctx(project)
    )
    const stored = getPaperById(project, first.paper!.id)
    assert.deepEqual(stored.authors, ['Real, A.', 'Real, B.'])
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})

test('fill-only: auto-generated bibtex IS replaced when caller supplies curated bibtex', () => {
  const project = tmpProject()
  try {
    const first = upsertPaperArtifact(
      'Paper',
      { authors: ['A'], year: 2024, doi: '10.1234/x' /* no bibtex */ },
      ctx(project)
    )
    assert.equal(first.paper!.bibtexIsAutoGenerated, true)

    const curated = '@article{x, title={Paper}, author={A}, year={2024}, keywords={curated}}'
    upsertPaperArtifact(
      'Paper',
      {
        authors: ['A'],
        year: 2024,
        doi: '10.1234/x',
        bibtex: curated
      },
      ctx(project)
    )
    const stored = getPaperById(project, first.paper!.id)
    assert.equal(stored.bibtex, curated)
    assert.equal(stored.bibtexIsAutoGenerated, false)
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})

test('fill-only: identityConfidence upgrades only, never downgrades', () => {
  const project = tmpProject()
  try {
    const first = upsertPaperArtifact(
      'Paper',
      {
        authors: ['A'],
        year: 2024,
        doi: '10.1234/x',
        identityConfidence: 'high'
      },
      ctx(project)
    )

    upsertPaperArtifact(
      'Paper',
      {
        authors: ['A'],
        year: 2024,
        doi: '10.1234/x',
        identityConfidence: 'low'
      },
      ctx(project)
    )
    const stored = getPaperById(project, first.paper!.id)
    assert.equal(stored.identityConfidence, 'high', 'must not downgrade')
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})

test('fill-only: identityConfidence upgrades low → high when DOI becomes available', () => {
  const project = tmpProject()
  try {
    const first = upsertPaperArtifact(
      'Paper',
      {
        authors: ['Smith'],
        year: 2024,
        citeKey: 'smith2024',
        identityConfidence: 'low'
      },
      ctx(project)
    )

    upsertPaperArtifact(
      'Paper',
      {
        authors: ['Smith'],
        year: 2024,
        citeKey: 'smith2024',
        doi: '10.1234/real',
        identityConfidence: 'high'
      },
      ctx(project)
    )
    const stored = getPaperById(project, first.paper!.id)
    assert.equal(stored.identityConfidence, 'high')
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})

test('fill-only: externalSource preserves original (first-wins on dedup)', () => {
  const project = tmpProject()
  try {
    // First write came from agent literature-search.
    const first = upsertPaperArtifact(
      'Paper',
      {
        authors: ['A'],
        year: 2024,
        doi: '10.1234/x',
        externalSource: 'literature-search'
      },
      ctx(project)
    )

    // Second write claims the paper as a BibTeX import — should NOT clobber.
    upsertPaperArtifact(
      'Paper',
      {
        authors: ['A'],
        year: 2024,
        doi: '10.1234/x',
        externalSource: 'bibtex-import'
      },
      ctx(project)
    )
    const stored = getPaperById(project, first.paper!.id)
    assert.equal(stored.externalSource, 'literature-search')
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})

test('tags are merged (union), not replaced', () => {
  const project = tmpProject()
  try {
    const first = upsertPaperArtifact(
      'Paper',
      { authors: ['A'], year: 2024, doi: '10.1234/x', tags: ['nlp', 'transformer'] },
      ctx(project)
    )

    upsertPaperArtifact(
      'Paper',
      { authors: ['A'], year: 2024, doi: '10.1234/x', tags: ['transformer', 'attention'] },
      ctx(project)
    )
    const stored = getPaperById(project, first.paper!.id)
    assert.deepEqual(stored.tags.sort(), ['attention', 'nlp', 'transformer'])
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})

// ─── No-op merge ─────────────────────────────────────────────────────────

// ─── Provenance override (RFC-006 review comment #1) ────────────────────

test('provenance override: importer can mark source=import / extractedFrom=file-import', () => {
  const project = tmpProject()
  try {
    // Simulates a BibTeX importer call: externalSource is set, but the
    // caller supplies a provenance override so the paper is correctly
    // labelled as an import rather than an agent product.
    const result = upsertPaperArtifact(
      'Imported Paper',
      {
        authors: ['Smith'],
        year: 2024,
        doi: '10.1234/imp',
        externalSource: 'bibtex-import',
        provenance: { source: 'import', extractedFrom: 'file-import' }
      },
      ctx(project)
    )
    assert.equal(result.success, true)
    assert.equal(result.paper!.provenance.source, 'import')
    assert.equal(result.paper!.provenance.extractedFrom, 'file-import')
    // sessionId is always taken from CLIContext, not from the override.
    assert.equal(result.paper!.provenance.sessionId, 'test-session')
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})

test('no provenance override + externalSource → falls back to agent-default (literature-search behavior preserved)', () => {
  const project = tmpProject()
  try {
    const result = upsertPaperArtifact(
      'Agent-Searched Paper',
      {
        authors: ['Smith'],
        year: 2024,
        doi: '10.1234/ag',
        externalSource: 'literature-search'
        // no provenance override
      },
      ctx(project)
    )
    assert.equal(result.paper!.provenance.source, 'agent')
    assert.equal(result.paper!.provenance.extractedFrom, 'agent-response')
    assert.equal(result.paper!.provenance.agentId, 'literature-team')
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})

test('no provenance override + no externalSource → user-default', () => {
  const project = tmpProject()
  try {
    const result = upsertPaperArtifact(
      'Manual Paper',
      { authors: ['Smith'], year: 2024, doi: '10.1234/m' },
      ctx(project)
    )
    assert.equal(result.paper!.provenance.source, 'user')
    assert.equal(result.paper!.provenance.extractedFrom, 'user-input')
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})

test('partial provenance override: agentId override accepted, other fields auto-derived', () => {
  const project = tmpProject()
  try {
    const result = upsertPaperArtifact(
      'Paper',
      {
        authors: ['Smith'],
        year: 2024,
        doi: '10.1234/x',
        externalSource: 'literature-search',
        provenance: { agentId: 'custom-agent' }
        // source / extractedFrom omitted → fall back to auto
      },
      ctx(project)
    )
    assert.equal(result.paper!.provenance.source, 'agent')
    assert.equal(result.paper!.provenance.agentId, 'custom-agent')
    assert.equal(result.paper!.provenance.extractedFrom, 'agent-response')
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})

test('bit-identical re-upsert is a no-op write (still reports wasDeduped=true)', () => {
  const project = tmpProject()
  try {
    const first = upsertPaperArtifact(
      'Paper',
      {
        authors: ['Smith', 'Jones'],
        year: 2024,
        doi: '10.1234/x',
        abstract: 'abstract',
        venue: 'NeurIPS',
        tags: ['nlp']
      },
      ctx(project)
    )
    const updatedAtBefore = first.paper!.updatedAt

    // Sleep a hair to ensure any spurious write would shift updatedAt.
    const start = Date.now()
    while (Date.now() - start < 5) { /* spin */ }

    const second = upsertPaperArtifact(
      'Paper',
      {
        authors: ['Smith', 'Jones'],
        year: 2024,
        doi: '10.1234/x',
        abstract: 'abstract',
        venue: 'NeurIPS',
        tags: ['nlp']
      },
      ctx(project)
    )
    assert.equal(second.wasDeduped, true)
    // No-op means updatedAt unchanged (no artifactUpdate fired).
    const stored = getPaperById(project, first.paper!.id)
    assert.equal(stored.updatedAt, updatedAtBefore, 'updatedAt should not move on no-op')
  } finally {
    rmSync(project, { recursive: true, force: true })
  }
})
