import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { createHash } from 'crypto'
import { trace as otelTrace } from '@opentelemetry/api'
import { createArtifactLedgerWriter, type ArtifactOp } from '../ledger/artifact-ledger.js'
import { readArtifactFromFile } from './artifact-files.js'
import { getArtifacts, upsertIndexEntry, removeIndexEntry } from './indexer.js'
import { writeArtifactToFile, removeArtifactFile, primaryFileRel } from './artifact-writer.js'
import { getSharedLocalActor } from '../sharing/identity.js'
import {
  PATHS,
  AGENT_MD_ID,
  AGENT_MD_MAX_CHARS,
  type Actor,
  type Artifact,
  type ArtifactType,
  type CLIContext,
  type NoteArtifact,
  type PaperArtifact,
  type Provenance,
  type DataSchema,
  type SessionSummary
} from '../types.js'

/**
 * RFC-013: in a SHARED project, the local actor that should own newly created
 * artifacts (drives the per-actor subdir + attribution). Undefined for
 * solo/unshared projects → artifacts stay flat (back-compat). Read fresh per
 * create; artifact creation is not a hot path.
 */
function resolveSharingActor(projectPath: string): Actor | undefined {
  return getSharedLocalActor(projectPath)
}

export interface ArtifactFileRecord<T extends Artifact = Artifact> {
  artifact: T
  filePath: string
}

/**
 * Tolerant readdir: returns [] when the directory can't be scanned.
 * Swallows EPERM (macOS TCC denial on iCloud/protected dirs), ENOENT
 * (race with delete), and ENOTDIR — anything else is re-thrown. A single
 * warning is emitted per path per process so the failure is still visible.
 */
const _warnedReaddirPaths = new Set<string>()
function safeReaddir(dir: string): string[] {
  try {
    return readdirSync(dir)
  } catch (err: any) {
    const code = err?.code
    if (code === 'EPERM' || code === 'ENOENT' || code === 'ENOTDIR' || code === 'EACCES') {
      if (!_warnedReaddirPaths.has(dir)) {
        _warnedReaddirPaths.add(dir)
        console.warn(`[memory-v2] cannot read artifact dir (${code}): ${dir}`)
      }
      return []
    }
    throw err
  }
}

export interface LegacyMigrationResult {
  updatedFiles: number
  convertedLiteratureType: number
  removedDataNameField: number
}

export type CreateArtifactInput =
  | {
      type: 'note'
      title: string
      content: string
      filePath?: string
      tags?: string[]
      summary?: string
      provenance?: Partial<Provenance>
    }
  | {
      type: 'paper'
      title: string
      authors: string[]
      abstract: string
      citeKey: string
      doi: string
      bibtex: string
      bibtexIsAutoGenerated?: boolean
      year?: number
      venue?: string
      url?: string
      pdfUrl?: string
      tags?: string[]
      summary?: string
      provenance?: Partial<Provenance>
      searchKeywords?: string[]
      externalSource?: string
      relevanceScore?: number
      citationCount?: number
      enrichmentSource?: string
      enrichedAt?: string
      // Literature study fields
      subTopic?: string
      keyFindings?: string[]
      relevanceJustification?: string
      addedInRound?: string
      addedByTask?: string
      fulltextPath?: string
      identityConfidence?: 'high' | 'medium' | 'low'
      arxivId?: string
      pubmedId?: string
      pmcId?: string
      semanticScholarId?: string
    }
  | {
      type: 'data'
      title: string
      filePath: string
      mimeType?: string
      schema?: DataSchema
      runId?: string
      runLabel?: string
      tags?: string[]
      summary?: string
      provenance?: Partial<Provenance>
    }
  | {
      type: 'web-content'
      title: string
      url: string
      content: string
      fetchedAt?: string
      tags?: string[]
      summary?: string
      provenance?: Partial<Provenance>
    }
  | {
      type: 'tool-output'
      title: string
      toolName: string
      outputPath?: string
      outputText?: string
      tags?: string[]
      summary?: string
      provenance?: Partial<Provenance>
    }

export interface UpdateArtifactInput {
  title?: string
  tags?: string[]
  summary?: string
  content?: string
  filePath?: string
  mimeType?: string
  schema?: unknown
  runId?: string
  runLabel?: string
  url?: string
  fetchedAt?: string
  toolName?: string
  outputPath?: string
  outputText?: string
  authors?: string[]
  abstract?: string
  citeKey?: string
  doi?: string
  bibtex?: string
  bibtexIsAutoGenerated?: boolean
  year?: number
  venue?: string
  pdfUrl?: string
  searchKeywords?: string[]
  externalSource?: string
  relevanceScore?: number
  citationCount?: number
  enrichmentSource?: string
  enrichedAt?: string
  subTopic?: string
  keyFindings?: string[]
  relevanceJustification?: string
  addedInRound?: string
  addedByTask?: string
  fulltextPath?: string
  identityConfidence?: 'high' | 'medium' | 'low'
  arxivId?: string
  pubmedId?: string
  pmcId?: string
  semanticScholarId?: string
}

function nowIso(): string {
  return new Date().toISOString()
}

function ensureDir(dir: string): void {
  mkdirSync(dir, { recursive: true })
}

function readJson<T>(filePath: string, fallback: T): T {
  try {
    const raw = readFileSync(filePath, 'utf-8')
    return JSON.parse(raw) as T
  } catch {
    return fallback
  }
}

function writeJson(filePath: string, value: unknown): void {
  ensureDir(dirname(filePath))
  writeFileSync(filePath, JSON.stringify(value, null, 2), 'utf-8')
}

function resolveArtifactDirs(projectPath: string): Array<{ type: ArtifactType; dir: string }> {
  return [
    { type: 'note', dir: join(projectPath, PATHS.notes) },
    { type: 'paper', dir: join(projectPath, PATHS.papers) },
    { type: 'data', dir: join(projectPath, PATHS.data) },
    { type: 'web-content', dir: join(projectPath, PATHS.webContent) },
    { type: 'tool-output', dir: join(projectPath, PATHS.toolOutputs) }
  ]
}

// readArtifactFromFile + artifact normalization now live in artifact-files.ts
// (shared by the indexer without a circular import). Re-exported for callers
// that historically imported it from this module.
export { readArtifactFromFile }

function mergeProvenance(context: CLIContext, override?: Partial<Provenance>): Provenance {
  return {
    source: override?.source ?? 'user',
    sessionId: override?.sessionId ?? context.sessionId,
    agentId: override?.agentId,
    extractedFrom: override?.extractedFrom ?? 'user-input',
    messageId: override?.messageId
  }
}

/**
 * Ensure the special agent-md note exists. Auto-creates it if missing.
 * Called during project initialization so the user always has agent.md available.
 */
export function ensureAgentMd(projectPath: string): void {
  const now = nowIso()
  const artifact: NoteArtifact = {
    id: AGENT_MD_ID,
    type: 'note',
    title: 'agent.md',
    content: '## User Instructions\n\n\n\n## Agent Memory\n',
    tags: ['pinned'],
    summary: 'User instructions and agent long-term memory. Injected into agent context every turn.',
    provenance: {
      source: 'user',
      sessionId: 'init',
      extractedFrom: 'user-input'
    },
    createdAt: now,
    updatedAt: now
  }
  // Skip if already present at the current location, the pre-rename location
  // (`notes/agent-md.md` — still read by the location-agnostic index walk), OR
  // as legacy JSON. Don't double-create (RFC-014 §4.2/§8).
  const candidates = [
    join(projectPath, primaryFileRel(artifact)),       // rp-artifacts/notes/agent-md.md
    join(projectPath, 'notes', `${AGENT_MD_ID}.md`),   // pre-rename root location
    join(projectPath, PATHS.notes, `${AGENT_MD_ID}.json`), // legacy JSON
  ]
  if (candidates.some(existsSync)) return

  writeArtifactToFile(projectPath, artifact)
  upsertIndexEntry(projectPath, artifact)
}

/**
 * Migrate legacy artifact shapes in place.
 * - type: "literature" -> "paper"
 * - data.name -> title (if title missing), then remove data.name
 */
export function migrateLegacyArtifacts(projectPath: string): LegacyMigrationResult {
  const dirs = resolveArtifactDirs(projectPath)
  let updatedFiles = 0
  let convertedLiteratureType = 0
  let removedDataNameField = 0

  for (const { dir } of dirs) {
    if (!existsSync(dir)) continue

    for (const file of safeReaddir(dir)) {
      if (!file.endsWith('.json')) continue
      const filePath = join(dir, file)
      let raw: Record<string, unknown>
      try {
        raw = JSON.parse(readFileSync(filePath, 'utf-8')) as Record<string, unknown>
      } catch {
        continue
      }

      let changed = false

      if (raw.type === 'literature') {
        raw.type = 'paper'
        convertedLiteratureType++
        changed = true
      }

      if (raw.type === 'data' && typeof raw.name === 'string') {
        if (typeof raw.title !== 'string' || raw.title.trim().length === 0) {
          raw.title = raw.name
        }
        delete raw.name
        removedDataNameField++
        changed = true
      }

      if (!changed) continue
      writeFileSync(filePath, JSON.stringify(raw, null, 2), 'utf-8')
      updatedFiles++
    }
  }

  return { updatedFiles, convertedLiteratureType, removedDataNameField }
}

export function createArtifact(input: CreateArtifactInput, context: CLIContext): ArtifactFileRecord {
  const id = crypto.randomUUID()
  const timestamp = nowIso()

  const provenance = mergeProvenance(context, input.provenance)
  // RFC-013: stamp the local actor in a shared project so the file lands in the
  // per-actor subdir (conflict prevention) and carries attribution. No-op for
  // solo projects. An explicitly supplied actor (e.g. re-import) is preserved.
  if (!provenance.actor) {
    const actor = resolveSharingActor(context.projectPath)
    if (actor) provenance.actor = actor
  }

  const common = {
    id,
    title: input.title,
    tags: input.tags ?? [],
    summary: input.summary,
    provenance,
    createdAt: timestamp,
    updatedAt: timestamp
  }

  let artifact: Artifact
  if (input.type === 'note') {
    artifact = {
      ...common,
      type: 'note',
      content: input.content,
      ...(input.filePath ? { filePath: input.filePath } : {})
    }
  } else if (input.type === 'paper') {
    artifact = {
      ...common,
      type: 'paper',
      authors: input.authors,
      abstract: input.abstract,
      citeKey: input.citeKey,
      doi: input.doi,
      bibtex: input.bibtex,
      bibtexIsAutoGenerated: input.bibtexIsAutoGenerated,
      year: input.year,
      venue: input.venue,
      url: input.url,
      pdfUrl: input.pdfUrl,
      searchKeywords: input.searchKeywords,
      externalSource: input.externalSource,
      relevanceScore: input.relevanceScore,
      citationCount: input.citationCount,
      enrichmentSource: input.enrichmentSource,
      enrichedAt: input.enrichedAt,
      subTopic: input.subTopic,
      keyFindings: input.keyFindings,
      relevanceJustification: input.relevanceJustification,
      addedInRound: input.addedInRound,
      addedByTask: input.addedByTask,
      fulltextPath: input.fulltextPath,
      identityConfidence: input.identityConfidence,
      arxivId: input.arxivId,
      pubmedId: input.pubmedId,
      semanticScholarId: input.semanticScholarId
    }
  } else if (input.type === 'data') {
    artifact = {
      ...common,
      type: 'data',
      filePath: input.filePath,
      mimeType: input.mimeType,
      schema: input.schema,
      runId: input.runId,
      runLabel: input.runLabel
    }
  } else if (input.type === 'web-content') {
    artifact = {
      ...common,
      type: 'web-content',
      url: input.url,
      content: input.content,
      fetchedAt: input.fetchedAt
    }
  } else {
    artifact = {
      ...common,
      type: 'tool-output',
      toolName: input.toolName,
      outputPath: input.outputPath,
      outputText: input.outputText
    }
  }

  // RFC-014 §6: write the real workspace file(s), then sync the derived index.
  const rel = writeArtifactToFile(context.projectPath, artifact)
  const filePath = join(context.projectPath, rel)
  upsertIndexEntry(context.projectPath, artifact)

  // Telemetry §8.1: append to artifact ledger. Best-effort — failures don't
  // affect the agent path. Trace context is auto-pulled by the writer;
  // turnId comes from CLIContext when the call is on a user turn.
  void writeArtifactLedgerCreate(context.projectPath, artifact, filePath, context.turnId)

  return { artifact, filePath }
}

export function listArtifacts(projectPath: string, types?: ArtifactType[]): Artifact[] {
  // RFC-014 §5: reads go through the derived index (built from workspace files
  // + legacy JSON). getArtifacts lazily builds the index on first use.
  const all = getArtifacts(projectPath)
  if (!types) return all
  const typeSet = new Set(types)
  return all.filter(a => typeSet.has(a.type))
}

/**
 * Resolve a mention key (id / id-prefix / paper citeKey / title substring) to an
 * artifact, via the index. Replaces the mention resolver's direct JSON scan
 * (RFC-014 §5.4). Match order mirrors the historical resolver.
 */
export function resolveArtifactByKey(projectPath: string, key: string, type?: ArtifactType): Artifact | null {
  const k = key.trim()
  const kl = k.toLowerCase()
  if (!kl) return null
  const candidates = getArtifacts(projectPath).filter(a => !type || a.type === type)
  for (const a of candidates) if (a.id === k) return a
  for (const a of candidates) if (a.id.toLowerCase().startsWith(kl)) return a
  for (const a of candidates) {
    if (a.type === 'paper') {
      const ck = a.citeKey.toLowerCase()
      if (ck === kl || ck.startsWith(kl)) return a
    }
  }
  for (const a of candidates) if ((a.title ?? '').toLowerCase().includes(kl)) return a
  return null
}

export function findArtifactById(projectPath: string, artifactId: string): ArtifactFileRecord | null {
  // RFC-014 §5: resolve via the index. `filePath` is the artifact's CANONICAL
  // backing file — recomputed from the artifact (primaryFileRel), not the path it
  // was scanned from. This keeps the path a pure function of the artifact
  // (no stored path; per-actor placement works), with one intentional caveat:
  // the indexer recognizes managed files ANYWHERE, but mutation always targets
  // the canonical path. So a managed file the user manually MOVED out of its
  // canonical location is still READ (scan-anywhere), but on the next edit it
  // re-materializes at the canonical path (the moved copy is not auto-removed),
  // and delete targets the canonical path. Treat hand-moved managed artifacts as
  // read-only until moved back. (Edits that change the canonical path itself —
  // citeKey/actor/data-location — DO clean up the old file; see updateArtifact.)
  const all = getArtifacts(projectPath)
  const match = all.find(a => a.id === artifactId) ?? all.find(a => a.id.startsWith(artifactId))
  if (!match) return null
  return { artifact: match, filePath: join(projectPath, primaryFileRel(match)) }
}

export function updateArtifact(projectPath: string, artifactId: string, patch: UpdateArtifactInput, turnId?: string): ArtifactFileRecord | null {
  const found = findArtifactById(projectPath, artifactId)
  if (!found) return null

  // Enforce character limit on agent.md
  if (found.artifact.id === AGENT_MD_ID && patch.content && patch.content.length > AGENT_MD_MAX_CHARS) {
    return null
  }

  const updated: Artifact = {
    ...found.artifact,
    ...patch,
    updatedAt: nowIso()
  } as Artifact

  // If this edit changes the artifact's canonical backing path — a paper's
  // citeKey, a data file's location, or the owning actor — remove the OLD file
  // first so the rename doesn't leave an orphan/duplicate. (The path is a pure
  // function of the artifact; see findArtifactById.)
  if (primaryFileRel(found.artifact) !== primaryFileRel(updated)) {
    removeArtifactFile(projectPath, found.artifact)
  }

  const rel = writeArtifactToFile(projectPath, updated)
  upsertIndexEntry(projectPath, updated)
  // Telemetry §8.1: ledger row for edit op.
  void writeArtifactLedgerUpdate(projectPath, updated, found.artifact, turnId)
  return { artifact: updated, filePath: join(projectPath, rel) }
}

export function deleteArtifact(projectPath: string, artifactId: string, turnId?: string): ArtifactFileRecord | null {
  const found = findArtifactById(projectPath, artifactId)
  if (!found) return null

  removeArtifactFile(projectPath, found.artifact)
  removeIndexEntry(projectPath, found.artifact.id)
  void writeArtifactLedgerDelete(projectPath, found.artifact, turnId)
  return found
}

function artifactSearchText(artifact: Artifact): string {
  if (artifact.type === 'note') {
    return `${artifact.title} ${artifact.summary ?? ''} ${artifact.content} ${(artifact.tags ?? []).join(' ')}`
  }
  if (artifact.type === 'paper') {
    return [
      artifact.title,
      artifact.summary ?? '',
      artifact.abstract,
      artifact.citeKey,
      artifact.doi,
      artifact.authors.join(' '),
      artifact.venue ?? '',
      artifact.url ?? '',
      (artifact.tags ?? []).join(' ')
    ].join(' ')
  }
  if (artifact.type === 'data') {
    return `${artifact.title} ${artifact.summary ?? ''} ${artifact.filePath} ${(artifact.tags ?? []).join(' ')}`
  }
  if (artifact.type === 'web-content') {
    return `${artifact.title} ${artifact.summary ?? ''} ${artifact.url} ${artifact.content} ${(artifact.tags ?? []).join(' ')}`
  }
  return `${artifact.title} ${artifact.summary ?? ''} ${artifact.toolName} ${artifact.outputPath ?? ''} ${artifact.outputText ?? ''} ${(artifact.tags ?? []).join(' ')}`
}

export interface ArtifactSearchHit {
  artifact: Artifact
  score: number
  match: string
}

export function searchArtifacts(projectPath: string, query: string, types?: ArtifactType[]): ArtifactSearchHit[] {
  const q = query.trim().toLowerCase()
  if (!q) return []

  const qTokens = q.split(/\s+/).filter(Boolean)
  const artifacts = listArtifacts(projectPath, types)

  const hits: ArtifactSearchHit[] = []
  for (const artifact of artifacts) {
    const hay = artifactSearchText(artifact).toLowerCase()
    const matched = qTokens.filter(token => hay.includes(token))
    if (matched.length === 0) continue
    hits.push({
      artifact,
      score: matched.length / qTokens.length,
      match: matched.slice(0, 6).join(', ')
    })
  }

  hits.sort((a, b) => b.score - a.score)
  return hits
}

export function normalizeDoi(doi: string): string {
  return doi.toLowerCase().replace(/^https?:\/\/doi\.org\//, '').trim()
}

export function findExistingPaperArtifact(
  projectPath: string,
  identity: { doi?: string | null; citeKey?: string | null; title: string; year?: number | null }
): PaperArtifact | null {
  const papers = listArtifacts(projectPath, ['paper'])
    .filter((item): item is PaperArtifact => item.type === 'paper')

  if (identity.doi) {
    const normalized = normalizeDoi(identity.doi)
    const byDoi = papers.find(p => p.doi && normalizeDoi(p.doi) === normalized)
    if (byDoi) return byDoi
  }

  if (identity.citeKey) {
    const key = identity.citeKey.trim().toLowerCase()
    const byCiteKey = papers.find(p => p.citeKey.trim().toLowerCase() === key)
    if (byCiteKey) return byCiteKey
  }

  const normalizedTitle = identity.title.toLowerCase().replace(/[^\w\s]/g, ' ').replace(/\s+/g, ' ').trim()
  const byTitleYear = papers.find(p => {
    const title = p.title.toLowerCase().replace(/[^\w\s]/g, ' ').replace(/\s+/g, ' ').trim()
    if (title !== normalizedTitle) return false
    if (!identity.year || !p.year) return true
    return p.year === identity.year
  })

  return byTitleYear ?? null
}

// ============================================================================
// Session Summary
// ============================================================================

export function writeSessionSummary(projectPath: string, summary: SessionSummary): void {
  const dir = join(projectPath, PATHS.sessionSummaries, summary.sessionId)
  ensureDir(dir)
  const filePath = join(dir, `${Date.now()}.json`)
  writeFileSync(filePath, JSON.stringify(summary, null, 2), 'utf-8')
}

export function readLatestSessionSummary(projectPath: string, sessionId: string): SessionSummary | null {
  const dir = join(projectPath, PATHS.sessionSummaries, sessionId)
  if (!existsSync(dir)) return null
  const files = safeReaddir(dir).filter(f => f.endsWith('.json'))
  if (files.length === 0) return null
  // Sort by numeric filename descending (ms epoch)
  files.sort((a, b) => {
    const na = parseInt(a, 10)
    const nb = parseInt(b, 10)
    return nb - na
  })
  return readJson<SessionSummary | null>(join(dir, files[0]), null)
}

// ============================================================================
// Compaction State
// ============================================================================
//
// Persists pi-coding-agent's running compaction summary across process
// restarts. Without this, a long-lived session that has already compacted
// once will pay the full re-summarization cost on the next compaction
// after every restart (the prior `previousSummary` argument is lost).
//
// Boundary trade-off: when the coordinator's first chat() after restart
// runs the orphan-recovery bootstrap, it injects session-summary content
// + replayed user/assistant turns into the head of the new agent
// transcript. Restoring the prior compactionSummary then asks pi to
// extend it with messages whose head-most content semantically overlaps
// with what the prior summary already covered. The LLM extension is
// expected to dedupe, but a small amount of content overlap is possible.
// We accept this trade-off — the alternative is to drop the persisted
// summary whenever a bootstrap occurs, which costs a re-summarization
// every restart and defeats the purpose of persistence.

export const COMPACTION_STATE_SCHEMA_VERSION = 1

export interface CompactionState {
  schemaVersion: typeof COMPACTION_STATE_SCHEMA_VERSION
  sessionId: string
  summary: string
  /** Number of compaction events that have contributed to this summary. */
  compactionCount: number
  /** ISO timestamp of the most recent write. */
  updatedAt: string
}

function compactionStateFile(projectPath: string, sessionId: string): string {
  return join(projectPath, PATHS.compactionState, `${sessionId}.json`)
}

/**
 * Read compaction state for a session. Returns null when:
 * - file is missing
 * - JSON is malformed
 * - schemaVersion does not match the current code
 * - required fields are missing
 *
 * Never throws — corrupt persisted state must not block agent startup.
 */
export function readCompactionState(projectPath: string, sessionId: string): CompactionState | null {
  const filePath = compactionStateFile(projectPath, sessionId)
  if (!existsSync(filePath)) return null
  const raw = readJson<unknown>(filePath, null)
  if (!raw || typeof raw !== 'object') return null
  const obj = raw as Partial<CompactionState>
  if (obj.schemaVersion !== COMPACTION_STATE_SCHEMA_VERSION) return null
  if (typeof obj.sessionId !== 'string' || obj.sessionId !== sessionId) return null
  if (typeof obj.summary !== 'string' || obj.summary.length === 0) return null
  if (typeof obj.compactionCount !== 'number') return null
  if (typeof obj.updatedAt !== 'string') return null
  return obj as CompactionState
}

/** Write compaction state. Best-effort — IO errors are swallowed. */
export function writeCompactionState(projectPath: string, state: CompactionState): void {
  try {
    writeJson(compactionStateFile(projectPath, state.sessionId), state)
  } catch {
    // Persistence failure must not block the agent.
  }
}

/** Delete compaction state for a session. No-op if file is missing. */
export function deleteCompactionState(projectPath: string, sessionId: string): void {
  const filePath = compactionStateFile(projectPath, sessionId)
  try {
    if (existsSync(filePath)) rmSync(filePath, { force: true })
  } catch {
    // ignore
  }
}

export interface OrphanMessage {
  role: 'user' | 'assistant'
  content: string
  timestamp: number
}

/**
 * Read user/assistant messages persisted to the session JSONL whose timestamp
 * is strictly greater than `cutoffMs`. Used by the coordinator's restart
 * bootstrap to recover any conversation turns that were never folded into a
 * SessionSummary before the previous process exited.
 */
export function readOrphanMessages(
  projectPath: string,
  sessionId: string,
  cutoffMs: number
): OrphanMessage[] {
  const file = join(projectPath, PATHS.sessions, `${sessionId}.jsonl`)
  if (!existsSync(file)) return []
  const result: OrphanMessage[] = []
  let raw: string
  try {
    raw = readFileSync(file, 'utf-8')
  } catch {
    return []
  }
  for (const line of raw.split('\n')) {
    if (!line) continue
    let msg: any
    try {
      msg = JSON.parse(line)
    } catch {
      continue
    }
    if (!msg || typeof msg !== 'object') continue
    if (msg.role !== 'user' && msg.role !== 'assistant') continue
    if (typeof msg.timestamp !== 'number' || msg.timestamp <= cutoffMs) continue
    if (typeof msg.content !== 'string' || msg.content.length === 0) continue
    result.push({ role: msg.role, content: msg.content, timestamp: msg.timestamp })
  }
  return result
}

// ─── Artifact ledger integration (telemetry-trace v0.10 §8.1) ─────────────
//
// Best-effort, fire-and-forget. The artifact JSON write is the read-side
// authority; ledger rows accrete an event log alongside.

function hashArtifactContent(artifact: Artifact): string {
  // Hash the canonical JSON for stable comparison; minor field reorders
  // shouldn't trigger spurious diffs because we serialize via JSON.stringify
  // which is field-order-stable from the same TypeScript shape.
  const json = JSON.stringify(artifact)
  return 'sha256:' + createHash('sha256').update(json).digest('hex')
}

function relPath(projectPath: string, filePath: string): string {
  // Workspace-relative POSIX path; tolerant of platform separators.
  const rel = filePath.startsWith(projectPath) ? filePath.slice(projectPath.length) : filePath
  return rel.replace(/\\/g, '/').replace(/^\/+/, '')
}

async function writeArtifactLedgerCreate(projectPath: string, artifact: Artifact, filePath: string, turnId?: string): Promise<void> {
  try {
    const writer = createArtifactLedgerWriter(projectPath)
    await writer.append({
      artifactId: artifact.id,
      version: 1,
      op: 'create',
      type: artifact.type,
      path: relPath(projectPath, filePath),
      contentHash: hashArtifactContent(artifact),
      versionBefore: null,
      initiator: pickInitiator(artifact),
      turnId
    })
  } catch {
    // Swallow — ledger failures must not block agent.
  }
}

async function writeArtifactLedgerUpdate(projectPath: string, after: Artifact, before: Artifact, turnId?: string): Promise<void> {
  try {
    const writer = createArtifactLedgerWriter(projectPath)
    await writer.append({
      artifactId: after.id,
      version: incrementVersion(after, before),
      op: 'edit',
      type: after.type,
      path: relPath(projectPath, ''),
      contentHash: hashArtifactContent(after),
      versionBefore: extractVersion(before),
      initiator: pickInitiator(after),
      turnId
    })
  } catch {
    // ignore
  }
}

async function writeArtifactLedgerDelete(projectPath: string, artifact: Artifact, turnId?: string): Promise<void> {
  try {
    const writer = createArtifactLedgerWriter(projectPath)
    await writer.append({
      artifactId: artifact.id,
      version: extractVersion(artifact) + 1,
      op: 'delete',
      type: artifact.type,
      path: '',
      contentHash: hashArtifactContent(artifact),
      versionBefore: extractVersion(artifact),
      initiator: pickInitiator(artifact),
      turnId
    })
  } catch {
    // ignore
  }
}

/**
 * Best-effort initiator inference from provenance. Falls back to 'tool' which
 * is the most common case under PiPilot (artifact ops happen via tool calls).
 */
function pickInitiator(a: Artifact): 'user' | 'assistant' | 'tool' | 'external' {
  const src = a.provenance?.source
  if (src === 'user') return 'user'
  if (src === 'agent') return 'assistant'
  if (src === 'import') return 'external'
  return 'tool'
}

function extractVersion(_a: Artifact): number {
  // Per-file artifact JSON doesn't yet carry a `version` field. We use 1 as
  // the synthetic baseline; real version increments come from the ledger
  // count, not the artifact JSON. P1 tradeoff per spec §14.2.
  return 1
}

function incrementVersion(_after: Artifact, _before: Artifact): number {
  // Same simplification: ledger version is a monotonic event count, derived
  // by analysis tools by counting prior rows for this artifactId, not stored
  // on the JSON. Returning 2 keeps the row well-formed; analysis SHOULD use
  // the row order, not this field.
  return 2
}

// Suppress unused-import warning when `otelTrace` isn't referenced directly
// here (the ledger writer pulls trace context via `trace.getActiveSpan()`).
void otelTrace
